[build]
builder = "maven"
buildCommand = "mvn clean package"

[deploy]
startCommand = "java -jar target/city-game-1.0-SNAPSHOT-jar-with-dependencies.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 