services:
  - type: web
    name: thecitygame
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: HOST
        value: thecitygame.onrender.com
      - key: PORT
        value: 10000 