services:
  - type: web
    name: thecitygame
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 1099
      - key: RENDER_EXTERNAL_HOSTNAME
        value: thecitygame.onrender.com 