services:
  - type: web
    name: thecitygame
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: RENDER_EXTERNAL_HOSTNAME
        value: thecitygame.onrender.com
    autoDeploy: true
    ports:
      - port: 1099
        protocol: tcp 