services:
  - type: web
    name: city-game-server
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 1099
      - key: RENDER_EXTERNAL_HOSTNAME
        value: thecitygame.onrender.com
    autoDeploy: true
    ports:
      - port: 1099
        protocol: tcp 